import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopPanel from "./ui/TopPanel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Planner Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen max-h-screen text-white`}>
        <TopPanel />
        {children}
      </body>
    </html>
  );
}
